services:
  - type: web
    name: alitqon-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python handlers/start.py"
    envVars:
      - key: GOOGLE_CREDS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
